---
name: Tailscale
version: 0.10.1.3
slug: tailscale
description: Zero config VPN for building secure networks
url: https://github.com/lmagyar/homeassistant-addon-tailscale
codenotary: lmagyar1973@gmail.com
ingress: true
ingress_port: 0
ingress_stream: true
startup: services
panel_icon: mdi:vpn
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
hassio_api: true
host_network: true
map:
  - share:rw
ports:
  1080/tcp: 1080
schema:
  advertise_exit_node: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  login_server: url?
  tags: ["match(^tag:[a-zA-Z0-9]-?[a-zA-Z0-9]+$)?"]
image: ghcr.io/lmagyar/{arch}-addon-tailscale
